apiVersion: v1
kind: Service
metadata:
  namespace: device-service
  labels:
    app: device-service
  name: device-service
spec:
  ports:
  
    - protocol: TCP
      port: 4000
      targetPort: 4000
   
   
  selector:
    app: device-service
  type: ClusterIP
